spring:
    datasource:
        url: "jdbc:log4jdbc:mysql://localhost:3306/spring-test?useUnicode=true&characterEncoding=utf-8"
        username: root
        password: Root%123
        driverClassName: net.sf.log4jdbc.DriverSpy
        maximumPoolSize: 5

server:
    port: 8085
    tomcat:
        maxKeepAliveRequests: 1
